"""MLLM video detectors: a reusable adapter for vision-language models that decide
real-vs-generated by emitting a verdict in their *text* output (no classifier head).

The audit needs a continuous p(generated) (for AUC / operating points), so `score()`
does not return a hard 0/1 from the parsed word: it reads the model's probability mass
on the `fake` vs `real` answer token at the verdict step (a soft, calibratable score),
falling back to the parsed label only if the verdict token cannot be located.
`features()` mean-pools the last decoder-layer hidden states into a per-clip embedding
for the uniform L2-LR readout. Subclass `MLLMDetector` with the model id, hub, prompts, and
answer tags (see skyra.py, videoveritas.py, ivy.py).
"""
from __future__ import annotations

import re
from typing import List, Optional, Tuple

import numpy as np

from vidaudit.detectors.base import Clip, Detector, DetectorSpec


# ---- pure, testable helpers (no model) -------------------------------------
def parse_verdict(text: str, real_word: str = "real", fake_word: str = "fake",
                  tags: Tuple[str, str] = ("<answer>", "</answer>")) -> Optional[str]:
    """Extract the verdict word from the answer span; None if absent/ambiguous.

    Looks inside the last `tags` span (case-insensitive); if there is no span, scans the
    whole text. Returns 'fake', 'real', or None (no verdict / both present)."""
    open_t, close_t = tags
    span = text
    m = re.findall(re.escape(open_t) + r"(.*?)" + re.escape(close_t), text, re.I | re.S)
    if m:
        span = m[-1]
    low = span.lower()
    has_fake, has_real = fake_word in low, real_word in low
    if has_fake and not has_real:
        return "fake"
    if has_real and not has_fake:
        return "real"
    return None


def verdict_prob(logit_fake: float, logit_real: float) -> float:
    """Softmax over the (fake, real) verdict-token logits -> p(generated)."""
    m = max(logit_fake, logit_real)
    ef, er = np.exp(logit_fake - m), np.exp(logit_real - m)
    return float(ef / (ef + er))


# ---- the reusable adapter --------------------------------------------------
class MLLMDetector(Detector):
    """Subclass and set `spec` + the prompt/model fields. Heavy: loads a 7-9B VLM."""

    model_id: str = ""
    hub: str = "hf"                  # "hf" | "modelscope" (where the weights live)
    system_prompt: str = ""
    user_prompt: str = "Is this video real or fake?"
    answer_tags: Tuple[str, str] = ("<answer>", "</answer>")
    real_word: str = "real"
    fake_word: str = "fake"

    def __init__(self, n_frames: int = 16, max_new_tokens: int = 2048, device=None):
        self.n_frames = n_frames
        self.max_new_tokens = max_new_tokens
        self._device = device
        self._model = None
        self._proc = None
        self._verdict_cache = None

    def _dev(self):
        import torch
        if self._device is None:
            self._device = ("cuda" if torch.cuda.is_available()
                            else "mps" if torch.backends.mps.is_available() else "cpu")
        return self._device

    def _resolve_model_path(self) -> str:
        """HF id as-is; ModelScope id -> a local snapshot dir (needs `pip install modelscope`)."""
        if self.hub == "modelscope":
            try:
                from modelscope import snapshot_download
            except ImportError as e:
                raise RuntimeError(f"{self.model_id} is hosted on ModelScope; "
                                   f"`pip install modelscope` to load it.") from e
            return snapshot_download(self.model_id)
        return self.model_id

    def _load(self):
        if self._model is None:
            import torch
            from transformers import AutoModelForImageTextToText, AutoProcessor
            path = self._resolve_model_path()
            self._proc = AutoProcessor.from_pretrained(path)
            model, info = AutoModelForImageTextToText.from_pretrained(
                path, torch_dtype=torch.bfloat16, output_loading_info=True)
            model = model.eval().to(self._dev())
            # Some Qwen-VL checkpoints omit lm_head.weight (tied to the input embeddings at
            # train time); transformers does not always re-tie it on load, leaving a randomly
            # initialized head that emits garbage. Re-tie from the embeddings when the head
            # was reported missing (missing_keys is a set on transformers 5.x, a list on 4.x).
            if any("lm_head" in str(k) for k in (info.get("missing_keys") or [])):
                import torch as _t
                with _t.no_grad():
                    emb = model.get_input_embeddings().weight
                    model.lm_head.weight.copy_(emb.to(model.lm_head.weight.device,
                                                       model.lm_head.weight.dtype))
            self._model = model
        return self._model, self._proc

    def load_weights(self, path: Optional[str] = None) -> None:
        """Override the HuggingFace id (or a local path) for the VLM checkpoint."""
        if path:
            self.model_id = path
        self._model = self._proc = self._verdict_cache = None  # force reload from the new id

    def _frames(self, clip: Clip):
        from vidaudit.detectors._extract import decode_pil
        return [im.convert("RGB") for im in decode_pil(clip.path, n_frames=self.n_frames)]

    def _inputs(self, frames):
        _, proc = self._load()
        content = [{"type": "image", "image": im} for im in frames]
        content.append({"type": "text", "text": self.user_prompt})
        messages = ([{"role": "system", "content": self.system_prompt}] if self.system_prompt else []) \
            + [{"role": "user", "content": content}]
        text = proc.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        return proc(text=[text], images=frames, return_tensors="pt").to(self._dev())

    def _verdict_token_ids(self):
        """All token ids that decode to the real/fake verdict word (any casing / leading
        space), found by scanning the tokenizer vocab. Robust to the model's emitted casing
        (e.g. 'Fake' vs 'fake'); cached on first use."""
        if self._verdict_cache is not None:
            return self._verdict_cache
        _, proc = self._load()
        fake, real = set(), set()
        for s, tid in proc.tokenizer.get_vocab().items():
            c = s.replace("Ġ", "").replace("▁", "").strip().lower()  # GPT-2 'G' / SP '_'
            if c == self.fake_word:
                fake.add(tid)
            elif c == self.real_word:
                real.add(tid)
        self._verdict_cache = (fake, real)
        return self._verdict_cache

    def score(self, clip: Clip) -> float:
        """p(generated): the softmax mass on the fake vs real verdict token at the answer
        step (soft, calibratable). Falls back to the parsed label if that token is not a
        single id / not locatable."""
        import torch
        model, proc = self._load()
        inputs = self._inputs(self._frames(clip))
        with torch.no_grad():
            out = model.generate(**inputs, max_new_tokens=self.max_new_tokens, do_sample=False,
                                 output_scores=True, return_dict_in_generate=True)
        gen = out.sequences[0, inputs["input_ids"].shape[1]:]
        gen_list = gen.tolist()
        text = proc.tokenizer.decode(gen, skip_special_tokens=True)
        fake_ids, real_ids = self._verdict_token_ids()
        verdict_ids = fake_ids | real_ids

        # soft score: the LAST verdict token the model emits is the final verdict (the
        # <answer>/<conclusion> word at the end, after any reasoning that may itself mention
        # "real"/"fake"). Read its fake-vs-real logits at that decode step.
        if out.scores is not None and verdict_ids:
            for i in range(len(gen_list) - 1, -1, -1):
                if gen_list[i] in verdict_ids:
                    logits = out.scores[i][0]
                    lf = max((logits[j].item() for j in fake_ids), default=-1e9)
                    lr = max((logits[j].item() for j in real_ids), default=-1e9)
                    if lf > -1e9 and lr > -1e9:
                        return verdict_prob(lf, lr)
                    break
        verdict = parse_verdict(text, self.real_word, self.fake_word, self.answer_tags)
        return {"fake": 1.0, "real": 0.0}.get(verdict, 0.5)   # hard fallback

    def features(self, clip: Clip) -> np.ndarray:
        """Mean-pooled last-layer decoder hidden states (per-clip VLM embedding)."""
        import torch
        model, _ = self._load()
        inputs = self._inputs(self._frames(clip))
        with torch.no_grad():
            out = model(**inputs, output_hidden_states=True)
        h = out.hidden_states[-1][0]                 # [seq, hidden]
        return h.float().mean(dim=0).cpu().numpy()
