"""MLLM video detectors: a reusable adapter for vision-language models that decide
real-vs-generated by emitting a verdict in their *text* output (no classifier head).

The audit needs a continuous p(generated) (for AUC / operating points), so `score()`
does not return a hard 0/1 from the parsed word: it reads the model's probability mass
on the `fake` vs `real` answer token at the verdict step (a soft, calibratable score),
falling back to the parsed label only if the verdict token cannot be located.
`features()` mean-pools the last decoder-layer hidden states into a per-clip embedding
for the uniform L2-LR readout. Subclass `MLLMDetector` with the model id, hub, prompts, and
answer tags (see skyra.py, videoveritas.py, ivy.py).
"""
from __future__ import annotations

import re
from typing import List, Optional, Tuple

import numpy as np

from vidaudit.detectors.base import Clip, Detector, DetectorSpec


# ---- pure, testable helpers (no model) -------------------------------------
def parse_verdict(text: str, real_word: str = "real", fake_word: str = "fake",
                  tags: Tuple[str, str] = ("<answer>", "</answer>")) -> Optional[str]:
    """Extract the verdict word from the answer span; None if absent/ambiguous.

    Looks inside the last `tags` span (case-insensitive); if there is no span, scans the
    whole text. Returns 'fake', 'real', or None (no verdict / both present)."""
    open_t, close_t = tags
    span = text
    m = re.findall(re.escape(open_t) + r"(.*?)" + re.escape(close_t), text, re.I | re.S)
    if m:
        span = m[-1]
    low = span.lower()
    has_fake, has_real = fake_word in low, real_word in low
    if has_fake and not has_real:
        return "fake"
    if has_real and not has_fake:
        return "real"
    return None


def verdict_prob(logit_fake: float, logit_real: float) -> float:
    """Softmax over the (fake, real) verdict-token logits -> p(generated)."""
    m = max(logit_fake, logit_real)
    ef, er = np.exp(logit_fake - m), np.exp(logit_real - m)
    return float(ef / (ef + er))


# ---- the reusable adapter --------------------------------------------------
class MLLMDetector(Detector):
    """Subclass and set `spec` + the prompt/model fields. Heavy: loads a 7-9B VLM."""

    model_id: str = ""
    hub: str = "hf"                  # "hf" | "modelscope" (where the weights live)
    system_prompt: str = ""
    user_prompt: str = "Is this video real or fake?"
    answer_tags: Tuple[str, str] = ("<answer>", "</answer>")
    real_word: str = "real"
    fake_word: str = "fake"

    def __init__(self, n_frames: int = 16, max_new_tokens: int = 1024, device=None):
        self.n_frames = n_frames
        self.max_new_tokens = max_new_tokens
        self._device = device
        self._model = None
        self._proc = None

    def _dev(self):
        import torch
        if self._device is None:
            self._device = ("cuda" if torch.cuda.is_available()
                            else "mps" if torch.backends.mps.is_available() else "cpu")
        return self._device

    def _resolve_model_path(self) -> str:
        """HF id as-is; ModelScope id -> a local snapshot dir (needs `pip install modelscope`)."""
        if self.hub == "modelscope":
            try:
                from modelscope import snapshot_download
            except ImportError as e:
                raise RuntimeError(f"{self.model_id} is hosted on ModelScope; "
                                   f"`pip install modelscope` to load it.") from e
            return snapshot_download(self.model_id)
        return self.model_id

    def _load(self):
        if self._model is None:
            import torch
            from transformers import AutoModelForImageTextToText, AutoProcessor
            path = self._resolve_model_path()
            self._proc = AutoProcessor.from_pretrained(path)
            self._model = AutoModelForImageTextToText.from_pretrained(
                path, torch_dtype=torch.bfloat16).eval().to(self._dev())
        return self._model, self._proc

    def load_weights(self, path: Optional[str] = None) -> None:
        """Override the HuggingFace id (or a local path) for the VLM checkpoint."""
        if path:
            self.model_id = path
        self._model = self._proc = None  # force reload from the new id

    def _frames(self, clip: Clip):
        from vidaudit.detectors._extract import decode_pil
        return [im.convert("RGB") for im in decode_pil(clip.path, n_frames=self.n_frames)]

    def _inputs(self, frames):
        _, proc = self._load()
        content = [{"type": "image", "image": im} for im in frames]
        content.append({"type": "text", "text": self.user_prompt})
        messages = ([{"role": "system", "content": self.system_prompt}] if self.system_prompt else []) \
            + [{"role": "user", "content": content}]
        text = proc.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        return proc(text=[text], images=frames, return_tensors="pt").to(self._dev())

    def _verdict_token_ids(self):
        """Single-token ids for the real/fake words (with and without a leading space)."""
        _, proc = self._load()
        tok = proc.tokenizer
        ids = {"fake": set(), "real": set()}
        for word, key in ((self.fake_word, "fake"), (self.real_word, "real")):
            for variant in (word, " " + word, word.capitalize(), " " + word.capitalize()):
                enc = tok.encode(variant, add_special_tokens=False)
                if len(enc) == 1:
                    ids[key].add(enc[0])
        return ids["fake"], ids["real"]

    def score(self, clip: Clip) -> float:
        """p(generated): the softmax mass on the fake vs real verdict token at the answer
        step (soft, calibratable). Falls back to the parsed label if that token is not a
        single id / not locatable."""
        import torch
        model, proc = self._load()
        inputs = self._inputs(self._frames(clip))
        with torch.no_grad():
            out = model.generate(**inputs, max_new_tokens=self.max_new_tokens, do_sample=False,
                                 output_scores=True, return_dict_in_generate=True)
        gen = out.sequences[0, inputs["input_ids"].shape[1]:]
        text = proc.tokenizer.decode(gen, skip_special_tokens=True)
        fake_ids, real_ids = self._verdict_token_ids()

        # soft score: first verdict token emitted after the answer-open tag
        open_id_seen = False
        open_tag = self.answer_tags[0]
        for i, tid in enumerate(gen.tolist()):
            if not open_id_seen:
                if open_tag in proc.tokenizer.decode(gen[:i + 1], skip_special_tokens=True):
                    open_id_seen = True
                continue
            if tid in fake_ids or tid in real_ids:
                logits = out.scores[i][0]
                lf = max((logits[j].item() for j in fake_ids), default=-1e9)
                lr = max((logits[j].item() for j in real_ids), default=-1e9)
                if lf > -1e9 and lr > -1e9:
                    return verdict_prob(lf, lr)
                break
        verdict = parse_verdict(text, self.real_word, self.fake_word, self.answer_tags)
        return {"fake": 1.0, "real": 0.0}.get(verdict, 0.5)   # hard fallback

    def features(self, clip: Clip) -> np.ndarray:
        """Mean-pooled last-layer decoder hidden states (per-clip VLM embedding)."""
        import torch
        model, _ = self._load()
        inputs = self._inputs(self._frames(clip))
        with torch.no_grad():
            out = model(**inputs, output_hidden_states=True)
        h = out.hidden_states[-1][0]                 # [seq, hidden]
        return h.float().mean(dim=0).cpu().numpy()
