"""Load the audited results CSV, derive the two verdicts, and render LEADERBOARD.md.

Verdict labels are computed from the numbers (vidaudit.audit.verdict), so the board
is reproducible from data rather than asserted. Special rows carry an explicit
`status` (leakage existence proof, excluded methods). Entry point: `build()`, wired
to `python run.py leaderboard`.
"""
from __future__ import annotations

import csv
from pathlib import Path
from typing import Optional

from vidaudit.audit import verdict as V

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CSV = ROOT / "leaderboard.csv"
DEFAULT_OUT = ROOT / "LEADERBOARD.md"

_NUMERIC = ("logo_id", "logo_ood", "rvr", "pauc10", "tpr1", "tpr01", "brier", "ece", "cost_ms")


def _f(x) -> Optional[float]:
    x = (x or "").strip()
    if not x:
        return None
    try:
        return float(x)
    except ValueError:
        return None


def load_rows(csv_path=None) -> list:
    csv_path = Path(csv_path) if csv_path else DEFAULT_CSV
    rows = []
    with open(csv_path, newline="") as fh:
        for r in csv.DictReader(fh):
            for k in _NUMERIC:
                r[k] = _f(r.get(k))
            r["ours"] = str(r.get("ours", "")).strip() in ("1", "true", "True")
            r["status"] = (r.get("status") or "").strip()
            rows.append(r)
    return rows


def classify(r) -> tuple:
    """Return (floor_verdict, deploy_tier, margin) for a row."""
    fv = r["status"] if r["status"] in ("leakage", "excluded") else V.floor_verdict(r["logo_ood"], r["rvr"])
    dt = V.deploy_tier(r["tpr01"])
    m = None if (r["logo_ood"] is None or r["rvr"] is None) else r["logo_ood"] - r["rvr"]
    return fv, dt, m


def _verdict_text(fv: str, dt: str) -> str:
    if fv == "certified":
        if dt == "usable":
            return "✅ Certified, usable"
        if dt == "collapses":
            return "⚠️ Certified, collapses @0.1%"
        if dt == "marginal":
            return "✅ Certified, marginal recall"
        return "✅ Certified"
    return {
        "caught": "❌ Caught (dataset identity)",
        "marginal": "❌ Near-floor (rides identity)",
        "weak": "⚠️ Above floor (weak)",
        "leakage": "🚩 Leakage (existence proof)",
        "excluded": "Excluded (no public weights)",
        "": "n/a",
    }.get(fv, fv or "n/a")


def _n(x, nd: int = 3) -> str:
    return "n/a" if x is None else f"{x:.{nd}f}"


def _name(r) -> str:
    return f"**{r['model']}**" + (" (ours)" if r["ours"] else "")


def render(rows) -> str:
    L = ["# VidAudit audited leaderboard", ""]
    L.append("_Generated by `python run.py leaderboard` from `leaderboard.csv`. Do not edit by hand._")
    L.append("")
    L.append("Matched 27k-clip GenVidBench cell, leave-one-generator-out (LOGO). Sorted by "
             "LOGO-OOD AUC (the headline number papers report); the RvR floor, above-floor margin, "
             "and TPR@0.1% columns decide whether that number is real.")
    L.append("")

    main = [r for r in rows if r["benchmark"] == "GenVidBench" and r["cell"] == "matched-27k"]
    board = [r for r in main if r["status"] == ""]
    board.sort(key=lambda r: (r["logo_ood"] is None, -(r["logo_ood"] or 0.0)))

    L.append("| # | Model | LOGO-OOD AUC ↑ | RvR floor | Margin ↑ | TPR@0.1% ↑ | Verdict |")
    L.append("|--:|---|:--:|:--:|:--:|:--:|---|")
    for i, r in enumerate(board, 1):
        fv, dt, m = classify(r)
        L.append(f"| {i} | {_name(r)} | {_n(r['logo_ood'])} | {_n(r['rvr'])} | "
                 f"{(f'{m:+.3f}') if m is not None else 'n/a'} | {_n(r['tpr01'])} | {_verdict_text(fv, dt)} |")
    L.append("")

    L.append("**Verdict key.** "
             "✅ Certified = clears its real-vs-real floor by a wide margin. "
             "✅ usable = also keeps recall at FPR 0.1%. "
             "⚠️ collapses @0.1% = strong AUC, near-zero deployable recall. "
             "❌ Caught = high RvR, the score rides dataset identity. "
             "❌ Near-floor = barely exceeds the floor. "
             "🚩 Leakage = relies on a confound the audit removes.")
    L.append("")
    L.append("**Columns.** LOGO-OOD: leave-one-generator-out AUC. RvR: real-vs-real floor "
             "(an artifact detector sits near 0.5; high means dataset-identity leakage). "
             "Margin: LOGO-OOD minus RvR. TPR@0.1%: recall at a 0.1% false-positive operating point.")
    L.append("")

    # other cells (cross-dataset / unmatched)
    other = [r for r in rows if r["status"] == "" and not (r["benchmark"] == "GenVidBench" and r["cell"] == "matched-27k")]
    if other:
        L.append("## Other cells")
        L.append("")
        L.append("| Model | Benchmark | Cell | LOGO-OOD | RvR | Margin | Notes |")
        L.append("|---|---|---|:--:|:--:|:--:|---|")
        for r in other:
            _, _, m = classify(r)
            L.append(f"| {_name(r)} | {r['benchmark']} | {r['cell']} | {_n(r['logo_ood'])} | "
                     f"{_n(r['rvr'])} | {(f'{m:+.3f}') if m is not None else 'n/a'} | {r.get('notes', '')} |")
        L.append("")

    # excluded
    excl = [r for r in rows if r["status"] == "excluded"]
    if excl:
        L.append("## Excluded")
        L.append("")
        for r in excl:
            L.append(f"- **{r['model']}** ({r['backbone']}): {r['notes']}.")
        L.append("")

    L.append("---")
    L.append("<sub>Native head or uniform L2-LR readout per method (see `readout` in "
             "`leaderboard.csv`). Bootstrap CIs, the full 116k cell, and the combined "
             "GenVidBench + AIGVDBench cross-dataset cell land here as the data package ships.</sub>")
    return "\n".join(L) + "\n"


def build(csv_path=None, out=None) -> Path:
    out = Path(out) if out else DEFAULT_OUT
    out.write_text(render(load_rows(csv_path)))
    return out


if __name__ == "__main__":
    print("rendered", build())
