#!/usr/bin/env python3
"""Generate the per-model verification matrix in README.md from ACTUAL test runs.

Runs the test suite, maps each model to its dedicated test file(s), and renders a markdown
table with a shields.io pill per model (tests passing / failing), spliced between the markers
    <!-- VERIFY-MATRIX:START -->  ...  <!-- VERIFY-MATRIX:END -->
so the "verified" claim in the README is generated, not hand-maintained.

    python scripts/gen_verification_matrix.py            # regenerate the README section
    python scripts/gen_verification_matrix.py --check     # CI: fail if README is stale or tests fail
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
_README = _REPO / "README.md"
_START = "<!-- VERIFY-MATRIX:START -->"
_END = "<!-- VERIFY-MATRIX:END -->"
_PILL_START = "<!-- TESTS-PILL:START -->"
_PILL_END = "<!-- TESTS-PILL:END -->"

# model display name -> (family, [test files]); the 3 MLLMs share one adapter test file.
_MODELS = [
    ("WaveRep", "forensic", ["test_waverep.py"]),
    ("D3", "appearance", ["test_d3.py"]),
    ("ReStraV", "appearance", ["test_restrav.py"]),
    ("CLIP", "appearance", ["test_clip.py"]),
    ("RAFT", "motion", ["test_raft.py"]),
    ("FVMD", "motion", ["test_fvmd.py"]),
    ("NSG-VD", "forensic", ["test_nsgvd.py"]),
    ("TemporalSpec", "codec", ["test_temporalspec.py"]),
    ("AIGVDet", "fusion", ["test_aigvdet.py"]),
    ("STALL", "fusion", ["test_stall.py"]),
    ("L3DE", "fusion", ["test_l3de.py"]),
    ("Skyra / VideoVeritas / Ivy", "mllm", ["test_mllm.py"]),
    ("MLP-Probe + trainer", "training", ["test_train.py"]),
    ("Toolkit core (audit, harness, data, CLI)", "framework",
     ["test_audit.py", "test_cli_integration.py", "test_data_package.py",
      "test_datasets.py", "test_detectors.py", "test_extract_guard.py",
      "test_fold_audit_row.py"]),
]

_LINE = re.compile(r"^(tests/test_\w+\.py)::\S+\s+(PASSED|FAILED|ERROR|XFAIL|XPASS|SKIPPED)")


def _run_pytest():
    """Return (per-file outcome counts, pytest returncode) by parsing `pytest -v`."""
    cp = subprocess.run(
        [sys.executable, "-m", "pytest", "tests/", "-v", "--no-header", "-p", "no:cacheprovider"],
        cwd=_REPO, capture_output=True, text=True)
    counts = defaultdict(lambda: defaultdict(int))
    for ln in cp.stdout.splitlines():
        m = _LINE.match(ln.strip())
        if m:
            counts[Path(m.group(1)).name][m.group(2)] += 1
    return counts, cp.returncode


def _pill(passed: int, bad: int) -> str:
    if bad:
        return f"![](https://img.shields.io/badge/tests-{bad}%20failing-red)"
    return f"![](https://img.shields.io/badge/tests-{passed}%20passing-brightgreen)"


def _matrix(counts) -> str:
    rows = ["| Model | Family | Tests | Status |", "|---|---|--:|:--|"]
    total_pass = total_bad = 0
    for name, family, files in _MODELS:
        # SKIPPED counts as non-failing so the matrix is stable across environments (e.g. a
        # test gated on ffmpeg PASSES where ffmpeg is present and SKIPS where it is not; either
        # way the row is "not failing", so a missing optional dep cannot flip --check to STALE).
        passed = sum(counts[f].get("PASSED", 0) + counts[f].get("XFAIL", 0)
                     + counts[f].get("SKIPPED", 0) for f in files)
        bad = sum(counts[f].get("FAILED", 0) + counts[f].get("ERROR", 0)
                  + counts[f].get("XPASS", 0) for f in files)
        total_pass += passed
        total_bad += bad
        rows.append(f"| {name} | {family} | {passed} | {_pill(passed, bad)} |")
    status = "all green" if total_bad == 0 else f"{total_bad} FAILING"
    head = (f"_Auto-generated by `scripts/gen_verification_matrix.py` from the test suite: "
            f"{total_pass} tests, {status}. Each row exercises that model's eval/train path on "
            f"synthetic inputs with no heavy weights or GPU._\n")
    return head + "\n" + "\n".join(rows) + "\n"


def _totals(counts):
    """Sum (passing, failing) across every model row (SKIPPED counts as non-failing)."""
    tp = tb = 0
    for _name, _family, files in _MODELS:
        tp += sum(counts[f].get("PASSED", 0) + counts[f].get("XFAIL", 0)
                  + counts[f].get("SKIPPED", 0) for f in files)
        tb += sum(counts[f].get("FAILED", 0) + counts[f].get("ERROR", 0)
                  + counts[f].get("XPASS", 0) for f in files)
    return tp, tb


def _header_pill(total_pass: int, total_bad: int) -> str:
    # A STATIC shields.io pill: renders on a private repo, unlike a live Actions badge whose
    # image request is unauthenticated. Swap back to the Actions badge once the repo is public.
    if total_bad:
        return f'  <img alt="tests" src="https://img.shields.io/badge/tests-{total_bad}%20failing-red">\n'
    return f'  <img alt="tests" src="https://img.shields.io/badge/tests-{total_pass}%20passing-brightgreen">\n'


def _splice(text: str, body: str, start: str = _START, end: str = _END) -> str:
    if start not in text or end not in text:
        raise SystemExit(f"markers {start} / {end} not found in README.md")
    pre, rest = text.split(start, 1)
    _, post = rest.split(end, 1)
    return f"{pre}{start}\n{body}{end}{post}"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="CI mode: exit nonzero if the README matrix is stale or any test fails")
    args = ap.parse_args(argv)

    counts, rc = _run_pytest()
    total_pass, total_bad = _totals(counts)
    new = _splice(_README.read_text(), _matrix(counts))
    new = _splice(new, _header_pill(total_pass, total_bad), _PILL_START, _PILL_END)

    if args.check:
        if rc != 0:  # report a real test failure as a test failure, not as a stale README
            print("pytest reported failures", file=sys.stderr)
            return 1
        if new != _README.read_text():
            print("README verification matrix is STALE; rerun scripts/gen_verification_matrix.py",
                  file=sys.stderr)
            return 1
        print("verification matrix is current and the suite is green")
        return 0

    _README.write_text(new)
    print(f"updated the verification matrix in {_README.name} (pytest rc={rc})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
